### ISSUE TITLE
Incompatible with "Recipe Essentials" from someaddon

### ISSUE THREAD

**Issue by eliasjurkeit** [Octo-Studios/nerb#11]
When using together with "Recipe Essentials" from someaddon, NERB doesn't seem to work (the recipe book is still there, which makes me assume that NERB's other features don't work as well). Both mods are on their newest versions available for Fabric 1.20.1.

MC Version: 1.20.1
Mod Loader: Fabric
Logs: https://gist.github.com/eliasjurkeit/a52f4deda94fdfc5fd5df7ecba49d2b8

Reproduce:
Just install NERB alongside "Recipe Essentials" from someaddon (only available on CurseForge) for MC Fabric 1.20.1.

**Comment by SSKirillSS** [comment]
Hi. RecipeEssentials completely overrides any modifications to the recipe book's UI. Since this mod also covers about 65% of what NERB does, you have two options:
1. Use RecipeEssentials' configuration to enable all features related to the recipe book. NERB will handle the remaining aspects not covered by RecipeEssentials.
2. Simply remove NERB.
