### ISSUE TITLE
[1.19.2] Removing the mod doesn't restore the crafting book.

### ISSUE THREAD

**Issue by togera13** [Octo-Studios/nerb#7]
I removed the mod in hopes of being able to see how to use the [Let's Do] & Farmer's Delight recipes in an easier way but the crafting book doesn't get restored when removing the mod...

Though tbh if there was a mod that added a way to see the recipes for the stuff specifically for the cooking mods then I'd be fine, but I need to remove this mod or we can't really use the cooking mods without trying to reverse engineer every recipe through JEI which was fine for everything else EXCEPT for cooking.

**Comment by SSKirillSS** [comment]
NERB deletes the recipe book data. This is literally how it works. If you then delete NERB, your recipe book will return, but you will need to reunlock all recipes. If after uninstalling NERB the recipe book button still does not appear - the reason is another mod installed in the modpack, because it too is trying to remove the recipe book. Storing data before the mod is installed makes no practical sense, so I don't think I can do anything about it.
